prompt: |
  Answer (feedbacks, proposes, questions:`*.question.json` and etc) in Russian language.
  Any content written to the project files is in English.

  Requirements:
  - For development use venv outside the project, in /opt/project

stages:
  code-review:
    approve: dialog
  contracts-review:
    approve: dialog
  documentation-review:
    approve: dialog
  testing:
    approve: dialog

extend:
  update-docs:
    communication: true
    before:
      - code-review
      - contracts-review
      - documentation-review
    after:
      - discovery-scope
    skills:
      - goga-tool
    prompt: |
      ARGUMENTS="mkdocs"

      Requirements:
      - Use `/tmp/changes.txt` for discover changelog
      - Commit changes after update docs
      - Ask the user if the decision to create a new documentation section or change structure is ambiguous

      Constraints:
      - Capture only the current state of the product, do not capture changes in the changelog format
